//
//  ViewController.swift
//  News App
//
//  Created by Pranav Gupta on 9/16/17.
//  Copyright © 2017 Pranav Gupta. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

// UserDefaults
// 1. VersionNum: Int = [1, 2, 3]
// 2. BiasingScore: Int = 0, 1, 2...100
// 3. UserID: String
// 4. DatabaseEntryNum: Int = 0, 1, 2...
// 5. NumArticleClicked: Int = 0, 1, 2...

// Sources View Controller TO DO,
// 1. Change NewsTagArray to actual tags that have been generated by Saif.
// 2. Use if let for checking if versionNum exists.
// 3. Add UI error message when user enters incorrect NewsTag.
